In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [6]:
df = pd.read_csv('train.csv')

In [7]:
df = df.drop(['Item_Identifier'], axis=1)
df = df.drop(['Outlet_Identifier'],axis=1)
df.head()

Item_Weight Item_Fat_Content  Item_Visibility              Item_Type  \
0         9.30          Low Fat         0.016047                  Dairy   
1         5.92          Regular         0.019278            Soft Drinks   
2        17.50          Low Fat         0.016760                   Meat   
3        19.20          Regular         0.000000  Fruits and Vegetables   
4         8.93          Low Fat         0.000000              Household   

   Item_MRP  Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0  249.8092                       1999      Medium               Tier 1   
1   48.2692                       2009      Medium               Tier 3   
2  141.6180                       1999      Medium               Tier 1   
3  182.0950                       1998         NaN               Tier 3   
4   53.8614                       1987        High               Tier 3   

         Outlet_Type  Item_Outlet_Sales  
0  Supermarket Type1          3735.1380  
1  Supermarket Type2           443.4228  
2  Supermarket Type1          2097.2700  
3      Grocery Store           732.3800  
4  Supermarket Type1           994.7052

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Item_Weight                7060 non-null   float64
 1   Item_Fat_Content           8523 non-null   object 
 2   Item_Visibility            8523 non-null   float64
 3   Item_Type                  8523 non-null   object 
 4   Item_MRP                   8523 non-null   float64
 5   Outlet_Establishment_Year  8523 non-null   int64  
 6   Outlet_Size                6113 non-null   object 
 7   Outlet_Location_Type       8523 non-null   object 
 8   Outlet_Type                8523 non-null   object 
 9   Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(5)
memory usage: 666.0+ KB


In [19]:
duplicates = df.duplicated().sum()
print(duplicates)

0


In [55]:
nan_cols = [i for i in df.columns if df[i].isnull().any()]
nan_cols

[]

In [22]:
df.isnull().sum()

Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [21]:
df.describe(include='all').T

count unique                    top  freq  \
Item_Weight                7060.0    NaN                    NaN   NaN   
Item_Fat_Content             8523      5                Low Fat  5089   
Item_Visibility            8523.0    NaN                    NaN   NaN   
Item_Type                    8523     16  Fruits and Vegetables  1232   
Item_MRP                   8523.0    NaN                    NaN   NaN   
Outlet_Establishment_Year  8523.0    NaN                    NaN   NaN   
Outlet_Size                  6113      3                 Medium  2793   
Outlet_Location_Type         8523      3                 Tier 3  3350   
Outlet_Type                  8523      4      Supermarket Type1  5577   
Item_Outlet_Sales          8523.0    NaN                    NaN   NaN   

                                  mean          std     min       25%  \
Item_Weight                  12.857645     4.643456   4.555   8.77375   
Item_Fat_Content                   NaN          NaN     NaN       NaN   
Item_Visibility               0.066132     0.051598     0.0  0.026989   
Item_Type                          NaN          NaN     NaN       NaN   
Item_MRP                    140.992782    62.275067   31.29   93.8265   
Outlet_Establishment_Year  1997.831867      8.37176  1985.0    1987.0   
Outlet_Size                        NaN          NaN     NaN       NaN   
Outlet_Location_Type               NaN          NaN     NaN       NaN   
Outlet_Type                        NaN          NaN     NaN       NaN   
Item_Outlet_Sales          2181.288914  1706.499616   33.29  834.2474   

                                50%        75%         max  
Item_Weight                    12.6      16.85       21.35  
Item_Fat_Content                NaN        NaN         NaN  
Item_Visibility            0.053931   0.094585    0.328391  
Item_Type                       NaN        NaN         NaN  
Item_MRP                   143.0128   185.6437    266.8884  
Outlet_Establishment_Year    1999.0     2004.0      2009.0  
Outlet_Size                     NaN        NaN         NaN  
Outlet_Location_Type            NaN        NaN         NaN  
Outlet_Type                     NaN        NaN         NaN  
Item_Outlet_Sales          1794.331  3101.2964  13086.9648

In [26]:
df['Item_Weight'].fillna(df['Item_Weight'].mean(), inplace = True)

In [32]:
#df['Outlet_Size'] = df['Outlet_Size'].replace(np.nan , 0)
df['Outlet_Size'] = df['Outlet_Size'].fillna(df['Outlet_Size'].mode()[0])

In [33]:
df.isnull().sum()

Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64

In [34]:
for feature in df.columns: 
    if df[feature].dtype == 'object': 
        df[feature] = pd.Categorical(df[feature]).codes

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Item_Weight                8523 non-null   float64
 1   Item_Fat_Content           8523 non-null   int8   
 2   Item_Visibility            8523 non-null   float64
 3   Item_Type                  8523 non-null   int8   
 4   Item_MRP                   8523 non-null   float64
 5   Outlet_Establishment_Year  8523 non-null   int64  
 6   Outlet_Size                8523 non-null   int8   
 7   Outlet_Location_Type       8523 non-null   int8   
 8   Outlet_Type                8523 non-null   int8   
 9   Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), int8(5)
memory usage: 374.7 KB


In [36]:
df

Item_Weight  Item_Fat_Content  Item_Visibility  Item_Type  Item_MRP  \
0           9.300                 1         0.016047          4  249.8092   
1           5.920                 2         0.019278         14   48.2692   
2          17.500                 1         0.016760         10  141.6180   
3          19.200                 2         0.000000          6  182.0950   
4           8.930                 1         0.000000          9   53.8614   
...           ...               ...              ...        ...       ...   
8518        6.865                 1         0.056783         13  214.5218   
8519        8.380                 2         0.046982          0  108.1570   
8520       10.600                 1         0.035186          8   85.1224   
8521        7.210                 2         0.145221         13  103.1332   
8522       14.800                 1         0.044878         14   75.4670   

      Outlet_Establishment_Year  Outlet_Size  Outlet_Location_Type  \
0                          1999            2                     0   
1                          2009            2                     2   
2                          1999            2                     0   
3                          1998            0                     2   
4                          1987            1                     2   
...                         ...          ...                   ...   
8518                       1987            1                     2   
8519                       2002            0                     1   
8520                       2004            3                     1   
8521                       2009            2                     2   
8522                       1997            3                     0   

      Outlet_Type  Item_Outlet_Sales  
0               1          3735.1380  
1               2           443.4228  
2               1          2097.2700  
3               0           732.3800  
4               1           994.7052  
...           ...                ...  
8518            1          2778.3834  
8519            1           549.2850  
8520            1          1193.1136  
8521            2          1845.5976  
8522            1           765.6700  

[8523 rows x 10 columns]

In [42]:
x = df.iloc[: , 0:9].values
y = df.iloc[:, -1].values

In [43]:
x

array([[9.30000000e+00, 1.00000000e+00, 1.60473010e-02, ...,
        2.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [5.92000000e+00, 2.00000000e+00, 1.92782160e-02, ...,
        2.00000000e+00, 2.00000000e+00, 2.00000000e+00],
       [1.75000000e+01, 1.00000000e+00, 1.67600750e-02, ...,
        2.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       ...,
       [1.06000000e+01, 1.00000000e+00, 3.51862710e-02, ...,
        3.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [7.21000000e+00, 2.00000000e+00, 1.45220646e-01, ...,
        2.00000000e+00, 2.00000000e+00, 2.00000000e+00],
       [1.48000000e+01, 1.00000000e+00, 4.48782800e-02, ...,
        3.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [44]:
y

array([3735.138 ,  443.4228, 2097.27  , ..., 1193.1136, 1845.5976,
        765.67  ])

In [45]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.02, random_state=0)

In [48]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [49]:
# Predict the X_test .
#Predicting the Test set result;  
y_pred= lr.predict(x_test)
#y_pred

In [51]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print('r2 score for perfect model is', r2)

r2 score for perfect model is 0.5710374165092134


In [52]:
df2 = pd.read_csv('test.csv')

In [53]:
df2 = df2.drop(['Item_Identifier'], axis=1)
df2 = df2.drop(['Outlet_Identifier'],axis=1)
df2.head()

Item_Weight Item_Fat_Content  Item_Visibility    Item_Type  Item_MRP  \
0       20.750          Low Fat         0.007565  Snack Foods  107.8622   
1        8.300              reg         0.038428        Dairy   87.3198   
2       14.600          Low Fat         0.099575       Others  241.7538   
3        7.315          Low Fat         0.015388  Snack Foods  155.0340   
4          NaN          Regular         0.118599        Dairy  234.2300   

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1   
1                       2007         NaN               Tier 2   
2                       1998         NaN               Tier 3   
3                       2007         NaN               Tier 2   
4                       1985      Medium               Tier 3   

         Outlet_Type  
0  Supermarket Type1  
1  Supermarket Type1  
2      Grocery Store  
3  Supermarket Type1  
4  Supermarket Type3

In [57]:
duplicates = df2.duplicated().sum()
print(duplicates)

0


In [58]:
nan_cols = [i for i in df2.columns if df2[i].isnull().any()]
nan_cols

['Item_Weight', 'Outlet_Size']

In [59]:
df2['Item_Weight'].fillna(df2['Item_Weight'].mean(), inplace = True)

In [60]:
df2['Outlet_Size'] = df2['Outlet_Size'].fillna(df2['Outlet_Size'].mode()[0])

In [62]:
for feature in df2.columns: 
    if df2[feature].dtype == 'object': 
        df2[feature] = pd.Categorical(df2[feature]).codes

In [63]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5681 entries, 0 to 5680
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Item_Weight                5681 non-null   float64
 1   Item_Fat_Content           5681 non-null   int8   
 2   Item_Visibility            5681 non-null   float64
 3   Item_Type                  5681 non-null   int8   
 4   Item_MRP                   5681 non-null   float64
 5   Outlet_Establishment_Year  5681 non-null   int64  
 6   Outlet_Size                5681 non-null   int8   
 7   Outlet_Location_Type       5681 non-null   int8   
 8   Outlet_Type                5681 non-null   int8   
dtypes: float64(3), int64(1), int8(5)
memory usage: 205.4 KB


In [64]:
# Predict the X_test .
#Predicting the Test set result;  
prediction= lr.predict(df2)
prediction

C:\Users\ABC\anaconda3\lib\site-packages\sklearn\base.py:413: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([2042.90635827, 1339.61477431, 2157.05195744, ..., 1708.59960253,
       3318.18733533, 1086.18589938])